### ISSUE TITLE
Does not compile on modern GCC (13)

### ISSUE THREAD

**Issue by Sanaki** [claunia/findcrcs#3]
Error as follows on GCC 13.2.1. I did get it to compile using clang 17.0.6 by modifying the makefile.
```
make
rm -rf *.o
g++ -O3 -Wall  -c crcutil-1.0/examples/interface.cc crcutil-1.0/code/*.cc -Icrcutil-1.0/code -Icrcutil-1.0/tests -Icrcutil-1.0/examples
In file included from crcutil-1.0/code/crc32c_sse4.h:23,
from crcutil-1.0/examples/interface.cc:20:
crcutil-1.0/code/crc32c_sse4_intrin.h: In function ‘unsigned int _mm_crc32_u8(unsigned int, unsigned char)’:
crcutil-1.0/code/crc32c_sse4_intrin.h:56:10: error: ‘__builtin_ia32_crc32qi’ was not declared in this scope; did you mean ‘__builtin_ia32_rorqi’?
56 |   return __builtin_ia32_crc32qi(__C, __V);
|          ^~~~~~~~~~~~~~~~~~~~~~
|          __builtin_ia32_rorqi
crcutil-1.0/code/crc32c_sse4_intrin.h: In function ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’:
crcutil-1.0/code/crc32c_sse4_intrin.h:62:10: error: ‘__builtin_ia32_crc32di’ was not declared in this scope; did you mean ‘__builtin_ia32_rorqi’?
62 |   return __builtin_ia32_crc32di(__C, __V);
|          ^~~~~~~~~~~~~~~~~~~~~~
|          __builtin_ia32_rorqi
In file included from crcutil-1.0/code/crc32c_sse4.h:23,
from crcutil-1.0/code/crc32c_sse4.cc:19:
crcutil-1.0/code/crc32c_sse4_intrin.h: In function ‘unsigned int _mm_crc32_u8(unsigned int, unsigned char)’:
crcutil-1.0/code/crc32c_sse4_intrin.h:56:10: error: ‘__builtin_ia32_crc32qi’ was not declared in this scope; did you mean ‘__builtin_ia32_rorqi’?
56 |   return __builtin_ia32_crc32qi(__C, __V);
|          ^~~~~~~~~~~~~~~~~~~~~~
|          __builtin_ia32_rorqi
crcutil-1.0/code/crc32c_sse4_intrin.h: In function ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’:
crcutil-1.0/code/crc32c_sse4_intrin.h:62:10: error: ‘__builtin_ia32_crc32di’ was not declared in this scope; did you mean ‘__builtin_ia32_rorqi’?
62 |   return __builtin_ia32_crc32di(__C, __V);
|          ^~~~~~~~~~~~~~~~~~~~~~
|          __builtin_ia32_rorqi
make[1]: *** [Makefile:77: crcutil.a] Error 1
make: *** [Makefile:20: all] Error 2
```
